using FluentAssertions;
using Harbora.Domain.Configuration;
using Harbora.Infrastructure.Configuration;
using Xunit;

namespace Harbora.Tests;

/// <summary>
/// C2 (2026-08-22 config-delivery plan): <see cref="EnvConfigFileEditor"/> — Laravel/Django/Node
/// <c>.env</c> files, keyed by the bare variable name with no nesting syntax at all.
/// </summary>
public class EnvConfigFileEditorTests
{
    private readonly EnvConfigFileEditor _editor = new();

    private const string Sample =
        "# generated by create-app, do not commit real secrets\n" +
        "APP_ENV=local\n" +
        "\n" +
        "DATABASE_URL=REPLACE_ME\n" +
        "API_KEY=\"quoted value with spaces\"\n";

    [Fact]
    public void Replacing_a_value_leaves_every_other_line_byte_identical()
    {
        var outcome = _editor.Apply(Sample, "DATABASE_URL", "postgres://user:pass@host/db");

        outcome.Ok.Should().BeTrue();
        var lines = outcome.NewContent!.Split('\n');
        lines[0].Should().Be("# generated by create-app, do not commit real secrets");
        lines[1].Should().Be("APP_ENV=local");
        lines[2].Should().Be("");
        lines[3].Should().Be("DATABASE_URL=postgres://user:pass@host/db");
        lines[4].Should().Be("API_KEY=\"quoted value with spaces\"");
    }

    [Fact]
    public void A_value_needing_quoting_is_quoted_so_the_file_stays_valid()
    {
        var outcome = _editor.Apply(Sample, "APP_ENV", "has space#and-hash");

        outcome.Ok.Should().BeTrue();
        outcome.NewContent.Should().Contain("APP_ENV=\"has space#and-hash\"");
    }

    [Fact]
    public void The_current_value_of_a_quoted_variable_is_unquoted_for_display()
    {
        var inspection = _editor.Inspect(Sample, "API_KEY");

        inspection.KeyFound.Should().BeTrue();
        inspection.CurrentValue.Should().Be("quoted value with spaces");
    }

    [Fact]
    public void Every_real_key_is_listed_for_a_missed_one()
    {
        var outcome = _editor.Apply(Sample, "MISSING_VAR", "x");

        outcome.Ok.Should().BeFalse();
        outcome.KeyFound.Should().BeFalse();
        outcome.KeyPaths.Should().BeEquivalentTo(["APP_ENV", "DATABASE_URL", "API_KEY"]);
    }

    [Fact]
    public void An_unterminated_quote_is_a_named_parse_failure()
    {
        const string broken = "DATABASE_URL=\"never closed\n";

        var outcome = _editor.Apply(broken, "DATABASE_URL", "x");

        outcome.Ok.Should().BeFalse();
        outcome.ParseError.Should().NotBeNull();
    }

    [Fact]
    public void Format_is_Env()
    {
        _editor.Format.Should().Be(ConfigFileFormat.Env);
    }
}
