namespace Harbora.Infrastructure.Deployments;

/// <summary>
/// Zero-config buildpacks. When a repo has no Dockerfile, this inspects the checkout and generates
/// a sensible Dockerfile for the detected stack — so "just give it a repo" works. The generated
/// image listens on <c>port</c> (via PORT / ASPNETCORE_URLS) to match the app's configured port.
/// Detection order is most-specific first; returns null when nothing recognisable is found.
/// </summary>
public static class Buildpacks
{
    public static BuildpackResult? Detect(string contextPath, int port)
    {
        bool Has(string file) => File.Exists(Path.Combine(contextPath, file));
        bool HasAny(params string[] files) => files.Any(Has);

        if (Has("package.json")) return Node(contextPath, port);
        if (FindCsproj(contextPath) is { } csproj) return DotNet(csproj, port);
        if (Has("go.mod")) return Go(port);
        if (HasAny("composer.json", "index.php")) return Php(contextPath, port);
        if (HasAny("requirements.txt", "pyproject.toml", "Pipfile")) return Python(contextPath, port);
        if (HasAny("index.html", "index.htm")) return Static();
        return null;
    }

    // --- Node ---
    private static BuildpackResult Node(string ctx, int port)
    {
        var (install, build, start) =
            File.Exists(Path.Combine(ctx, "pnpm-lock.yaml"))
                ? ("RUN corepack enable && pnpm install", "RUN pnpm run build || true", "pnpm start")
            : File.Exists(Path.Combine(ctx, "yarn.lock"))
                ? ("RUN corepack enable && yarn install --frozen-lockfile || yarn install", "RUN yarn build || true", "yarn start")
                : ("RUN npm install", "RUN npm run build --if-present", "npm start");

        var df =
            $"""
            # Auto-generated by Harbora (Node buildpack)
            FROM node:20-alpine
            WORKDIR /app
            COPY . .
            {install}
            {build}
            ENV NODE_ENV=production
            ENV PORT={port}
            EXPOSE {port}
            CMD ["sh", "-c", "{start}"]
            """;
        return new BuildpackResult(df, "Node.js");
    }

    // --- .NET ---
    private static BuildpackResult DotNet(string csprojRel, int port)
    {
        var assembly = Path.GetFileNameWithoutExtension(csprojRel);
        var df =
            $"""
            # Auto-generated by Harbora (.NET buildpack)
            FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
            WORKDIR /src
            COPY . .
            RUN dotnet publish "{csprojRel.Replace('\\', '/')}" -c Release -o /app

            FROM mcr.microsoft.com/dotnet/aspnet:9.0
            WORKDIR /app
            COPY --from=build /app ./
            ENV ASPNETCORE_URLS=http://+:{port}
            EXPOSE {port}
            ENTRYPOINT ["dotnet", "{assembly}.dll"]
            """;
        return new BuildpackResult(df, ".NET");
    }

    // --- Go ---
    private static BuildpackResult Go(int port)
    {
        var df =
            $"""
            # Auto-generated by Harbora (Go buildpack)
            FROM golang:1.22-alpine AS build
            WORKDIR /src
            COPY go.* ./
            RUN go mod download || true
            COPY . .
            RUN CGO_ENABLED=0 go build -o /app/server .

            FROM alpine:3.20
            RUN apk add --no-cache ca-certificates
            COPY --from=build /app/server /server
            ENV PORT={port}
            EXPOSE {port}
            CMD ["/server"]
            """;
        return new BuildpackResult(df, "Go");
    }

    // --- PHP ---
    private static BuildpackResult Php(string ctx, int port)
    {
        var composer = File.Exists(Path.Combine(ctx, "composer.json"))
            ? "RUN if [ -f composer.json ]; then curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && composer install --no-dev --no-interaction || true; fi"
            : "";
        var df =
            $"""
            # Auto-generated by Harbora (PHP buildpack)
            FROM php:8.3-apache
            RUN a2enmod rewrite
            # Serve on the app's port instead of 80.
            RUN sed -ri "s/Listen 80/Listen {port}/" /etc/apache2/ports.conf \
             && sed -ri "s/:80>/:{port}>/" /etc/apache2/sites-enabled/000-default.conf
            WORKDIR /var/www/html
            COPY . /var/www/html/
            {composer}
            EXPOSE {port}
            """;
        return new BuildpackResult(df, "PHP");
    }

    // --- Python ---
    private static BuildpackResult Python(string ctx, int port)
    {
        var entry = new[] { "app.py", "main.py", "wsgi.py", "server.py", "manage.py" }
            .FirstOrDefault(f => File.Exists(Path.Combine(ctx, f))) ?? "app.py";
        var install = File.Exists(Path.Combine(ctx, "requirements.txt"))
            ? "RUN pip install --no-cache-dir -r requirements.txt"
            : "RUN pip install --no-cache-dir . || true";
        var df =
            $"""
            # Auto-generated by Harbora (Python buildpack)
            FROM python:3.12-slim
            WORKDIR /app
            COPY . .
            {install}
            ENV PORT={port}
            EXPOSE {port}
            CMD ["python", "{entry}"]
            """;
        return new BuildpackResult(df, "Python");
    }

    /// <summary>Public entry for a forced static-site (Nginx) build, used by StaticSite deploys.</summary>
    public static BuildpackResult ForStaticSite() => Static();

    // --- Static site ---
    private static BuildpackResult Static()
    {
        var df =
            """
            # Auto-generated by Harbora (static buildpack)
            FROM nginx:alpine
            COPY . /usr/share/nginx/html
            EXPOSE 80
            """;
        return new BuildpackResult(df, "Static (Nginx)");
    }

    /// <summary>First .csproj (skipping bin/obj), preferring a web/api/server-looking project.</summary>
    private static string? FindCsproj(string contextPath)
    {
        var projects = Directory.EnumerateFiles(contextPath, "*.csproj", SearchOption.AllDirectories)
            .Where(p => !p.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}") &&
                        !p.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}"))
            .Select(p => Path.GetRelativePath(contextPath, p))
            .ToList();
        if (projects.Count == 0) return null;
        return projects.FirstOrDefault(p =>
                   p.Contains("web", StringComparison.OrdinalIgnoreCase) ||
                   p.Contains("api", StringComparison.OrdinalIgnoreCase) ||
                   p.Contains("server", StringComparison.OrdinalIgnoreCase))
               ?? projects[0];
    }
}

public readonly record struct BuildpackResult(string Dockerfile, string Stack);
