using Harbora.Domain.Common;

namespace Harbora.Infrastructure.Deployments;

/// <summary>
/// Zero-config buildpacks. When a repo has no Dockerfile, this inspects the checkout and generates
/// a sensible Dockerfile for the detected stack — so "just give it a repo" works. The generated
/// image listens on <c>port</c> (via PORT / ASPNETCORE_URLS) to match the app's configured port.
/// Detection order is most-specific first; returns null when nothing recognisable is found.
/// </summary>
public static class Buildpacks
{
    /// <summary>
    /// Python entry-point candidates, most-specific/likely first. `manage.py` is deliberately
    /// absent: `python manage.py` with no arguments prints usage and exits 0, so a Django repo
    /// "detected" through it would build, start, exit and restart forever under a restart policy of
    /// `UnlessStopped` — an honest "couldn't detect" beats a silent crash loop. This buildpack does
    /// not support Django; add a Dockerfile for one.
    /// </summary>
    private static readonly string[] PythonEntryCandidates =
        ["app.py", "main.py", "wsgi.py", "server.py", "bot.py", "run.py", "start.py", "__main__.py"];

    public static BuildpackResult? Detect(string contextPath, int port, ServiceKind kind = ServiceKind.Web)
    {
        bool Has(string file) => File.Exists(Path.Combine(contextPath, file));
        bool HasAny(params string[] files) => files.Any(Has);

        if (Has("package.json")) return Node(contextPath, port);
        if (FindCsproj(contextPath) is { } csproj) return DotNet(csproj, port);
        if (Has("go.mod")) return Go(port);
        if (HasAny("composer.json", "index.php")) return Php(contextPath, port);
        if (HasAny("requirements.txt", "pyproject.toml", "Pipfile")) return Python(contextPath, port, kind);
        if (HasAny("index.html", "index.htm")) return Static();
        return null;
    }

    /// <summary>
    /// Why detection found nothing, for the repos that look like a known stack but have no runnable
    /// entry point — so the operator learns what's missing rather than just that nothing was found.
    /// Null when there's nothing more specific to say than "nothing recognised".
    /// </summary>
    public static string? DetectionHint(string contextPath)
    {
        bool Has(string file) => File.Exists(Path.Combine(contextPath, file));
        if (!Has("requirements.txt") && !Has("pyproject.toml") && !Has("Pipfile")) return null;

        if (Has("manage.py"))
            return "found manage.py, which looks like Django — this buildpack does not auto-detect " +
                   "Django. Add a Dockerfile.";

        return "looks like a Python project (requirements.txt/pyproject.toml/Pipfile) but none of " +
               $"its recognised entry files were found ({string.Join(", ", PythonEntryCandidates)}). " +
               "Add a Dockerfile, or add one of those files.";
    }

    // --- Node ---
    private static BuildpackResult Node(string ctx, int port)
    {
        var (install, build, start) =
            File.Exists(Path.Combine(ctx, "pnpm-lock.yaml"))
                ? ("RUN corepack enable && pnpm install", "RUN pnpm run build || true", "pnpm start")
            : File.Exists(Path.Combine(ctx, "yarn.lock"))
                ? ("RUN corepack enable && yarn install --frozen-lockfile || yarn install", "RUN yarn build || true", "yarn start")
                : ("RUN npm install", "RUN npm run build --if-present", "npm start");

        var df =
            $"""
            # Auto-generated by Harbora (Node buildpack)
            FROM node:20-alpine
            WORKDIR /app
            COPY . .
            {install}
            {build}
            ENV NODE_ENV=production
            ENV PORT={port}
            EXPOSE {port}
            CMD ["sh", "-c", "{start}"]
            """;
        return new BuildpackResult(df, "Node.js");
    }

    // --- .NET ---
    private static BuildpackResult DotNet(string csprojRel, int port)
    {
        var assembly = Path.GetFileNameWithoutExtension(csprojRel);
        var df =
            $"""
            # Auto-generated by Harbora (.NET buildpack)
            FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
            WORKDIR /src
            COPY . .
            RUN dotnet publish "{csprojRel.Replace('\\', '/')}" -c Release -o /app

            FROM mcr.microsoft.com/dotnet/aspnet:9.0
            WORKDIR /app
            COPY --from=build /app ./
            ENV ASPNETCORE_URLS=http://+:{port}
            EXPOSE {port}
            ENTRYPOINT ["dotnet", "{assembly}.dll"]
            """;
        return new BuildpackResult(df, ".NET");
    }

    // --- Go ---
    private static BuildpackResult Go(int port)
    {
        var df =
            $"""
            # Auto-generated by Harbora (Go buildpack)
            FROM golang:1.22-alpine AS build
            WORKDIR /src
            COPY go.* ./
            RUN go mod download || true
            COPY . .
            RUN CGO_ENABLED=0 go build -o /app/server .

            FROM alpine:3.20
            RUN apk add --no-cache ca-certificates
            COPY --from=build /app/server /server
            ENV PORT={port}
            EXPOSE {port}
            CMD ["/server"]
            """;
        return new BuildpackResult(df, "Go");
    }

    // --- PHP ---
    private static BuildpackResult Php(string ctx, int port)
    {
        var composer = File.Exists(Path.Combine(ctx, "composer.json"))
            ? "RUN if [ -f composer.json ]; then curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && composer install --no-dev --no-interaction || true; fi"
            : "";
        var df =
            $"""
            # Auto-generated by Harbora (PHP buildpack)
            FROM php:8.3-apache
            RUN a2enmod rewrite
            # Serve on the app's port instead of 80.
            RUN sed -ri "s/Listen 80/Listen {port}/" /etc/apache2/ports.conf \
             && sed -ri "s/:80>/:{port}>/" /etc/apache2/sites-enabled/000-default.conf
            WORKDIR /var/www/html
            COPY . /var/www/html/
            {composer}
            EXPOSE {port}
            """;
        return new BuildpackResult(df, "PHP");
    }

    // --- Python ---
    private static BuildpackResult? Python(string ctx, int port, ServiceKind kind)
    {
        var entry = PythonEntryCandidates.FirstOrDefault(f => File.Exists(Path.Combine(ctx, f)));
        if (entry is null) return null; // No guessing — an image that can't start is worse than none.

        var install = File.Exists(Path.Combine(ctx, "requirements.txt"))
            ? "RUN pip install --no-cache-dir -r requirements.txt"
            : "RUN pip install --no-cache-dir . || true";

        var lines = new List<string>
        {
            "# Auto-generated by Harbora (Python buildpack)",
            "FROM python:3.12-slim",
            "WORKDIR /app",
            "COPY . .",
            install,
            // Python buffers stdout when it isn't a TTY. Without this, a working bot's print()
            // sits in the buffer and the panel's log view stays empty forever.
            "ENV PYTHONUNBUFFERED=1",
        };

        // A worker/cron/release task has nothing listening on a port — claiming one would be a
        // claim nobody can act on. ServicePlan.HasHttpHealthCheck already answers "does this kind
        // serve HTTP" (true for Private too: it listens, just not publicly), so reuse it instead of
        // a second list of kinds.
        if (ServicePlan.HasHttpHealthCheck(kind))
        {
            lines.Add($"ENV PORT={port}");
            lines.Add($"EXPOSE {port}");
        }

        lines.Add($"CMD [\"python\", \"{entry}\"]");

        return new BuildpackResult(string.Join('\n', lines), "Python", entry);
    }

    /// <summary>Public entry for a forced static-site (Nginx) build, used by StaticSite deploys.</summary>
    public static BuildpackResult ForStaticSite() => Static();

    // --- Static site ---
    private static BuildpackResult Static()
    {
        var df =
            """
            # Auto-generated by Harbora (static buildpack)
            FROM nginx:alpine
            COPY . /usr/share/nginx/html
            EXPOSE 80
            """;
        return new BuildpackResult(df, "Static (Nginx)");
    }

    /// <summary>First .csproj (skipping bin/obj), preferring a web/api/server-looking project.</summary>
    private static string? FindCsproj(string contextPath)
    {
        var projects = Directory.EnumerateFiles(contextPath, "*.csproj", SearchOption.AllDirectories)
            .Where(p => !p.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}") &&
                        !p.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}"))
            .Select(p => Path.GetRelativePath(contextPath, p))
            .ToList();
        if (projects.Count == 0) return null;
        return projects.FirstOrDefault(p =>
                   p.Contains("web", StringComparison.OrdinalIgnoreCase) ||
                   p.Contains("api", StringComparison.OrdinalIgnoreCase) ||
                   p.Contains("server", StringComparison.OrdinalIgnoreCase))
               ?? projects[0];
    }
}

/// <summary>
/// <paramref name="Entry"/> is the chosen entry point / start command when the stack has one worth
/// naming (currently just Python's <c>CMD</c> file) — null for stacks where "the stack" already is
/// the answer. Lets the pipeline log which guess it made instead of just which stack it picked.
/// </summary>
public readonly record struct BuildpackResult(string Dockerfile, string Stack, string? Entry = null);
