using Harbora.Application.Abstractions;
using Harbora.Domain.Services;
using Microsoft.Extensions.Logging;

namespace Harbora.Infrastructure.Services;

/// <summary>
/// Creates and removes the login an external grant uses, by running the engine's own client against
/// the database on its private network.
///
/// A one-off container rather than a connection from the panel: it needs no driver for every engine
/// Harbora supports, it reaches the database over the network the database is actually on, and it
/// leaves nothing behind. The statements come from <see cref="DatabaseGrantSql"/>, which refuses to
/// build anything out of a value it has not proved is safe.
/// </summary>
public sealed class DatabaseGrantExecutor(
    IDockerEngine docker,
    ISecretProtector protector,
    ILogger<DatabaseGrantExecutor> logger)
{
    public async Task<(bool Ok, string? Error)> CreateAsync(
        ManagedService service, string networkName, string username, string password, CancellationToken ct)
    {
        if (!DatabaseGrantSql.Supports(service.Type))
            return (false, DatabaseGrantSql.UnsupportedReason(service.Type));

        var command = DatabaseGrantSql.Create(
            service.Type, service.ContainerName, service.InternalPort,
            service.Username, service.DatabaseName, username, password);

        // Null means a value failed the safety check. Refused rather than escaped: everything here
        // is generated by Harbora, so anything outside the alphabet is a bug or an attack.
        if (command is null) return (false, "That database's details cannot be used to make a login.");

        var run = await RunAsync(service, networkName, command, "create the login", ct);
        return (run.Ok, run.Error);
    }

    /// <summary>
    /// Replaces the password on a login that is already there.
    ///
    /// <para>
    /// Unsupported engines are refused rather than silently accepted, unlike <see cref="DropAsync"/>:
    /// a drop that has nothing to drop has already achieved what it was for, but a rotation that
    /// changed nothing must not come back as success — the caller hands the returned password to a
    /// person on the strength of that answer.
    /// </para>
    ///
    /// <para>
    /// This is the one caller that needs <c>Answered</c>, which is why it returns it. A refusal the
    /// client reported and a refusal nobody reported are different facts about a customer's
    /// database, and only the first of them means the old password is still the live one.
    /// </para>
    /// </summary>
    public Task<(bool Ok, string? Error, bool Answered)> RotateAsync(
        ManagedService service, string networkName, string username, string password, CancellationToken ct)
    {
        if (!DatabaseGrantSql.Supports(service.Type))
            return Task.FromResult((false, (string?)DatabaseGrantSql.UnsupportedReason(service.Type), true));

        var command = DatabaseGrantSql.Rotate(
            service.Type, service.ContainerName, service.InternalPort,
            service.Username, service.DatabaseName, username, password);

        // Nothing was built, so nothing was run — the answer is as certain as it gets.
        if (command is null)
            return Task.FromResult((false, (string?)"That login's details cannot be used in a statement.", true));

        return RunAsync(service, networkName, command, "change the login's password", ct);
    }

    public async Task<(bool Ok, string? Error)> DropAsync(
        ManagedService service, string networkName, string username, CancellationToken ct)
    {
        if (!DatabaseGrantSql.Supports(service.Type)) return (true, null);

        var command = DatabaseGrantSql.Drop(
            service.Type, service.ContainerName, service.InternalPort,
            service.Username, service.DatabaseName, username);

        if (command is null) return (false, "That login's name cannot be used in a statement.");

        var run = await RunAsync(service, networkName, command, "remove the login", ct);
        return (run.Ok, run.Error);
    }

    /// <param name="what">
    /// The operation, in the words the operator reads. It goes into the refusal and into the log.
    /// </param>
    /// <returns>
    /// <c>Answered</c> is whether the client ran and gave a verdict. False means the container was
    /// started and no exit code ever came back — the daemon went away, the stream broke, the token
    /// was cancelled while the logs drained — and in that case the statement may have reached the
    /// database before things went wrong. A caller holding a secret that statement carried has to
    /// treat it as possibly live; saying only "could not be reached" invites the opposite reading.
    /// </returns>
    private async Task<(bool Ok, string? Error, bool Answered)> RunAsync(
        ManagedService service, string networkName, GrantCommand command, string what, CancellationToken ct)
    {
        string adminPassword;
        try { adminPassword = protector.Unprotect(service.EncryptedPassword); }
        catch (Exception ex)
        {
            logger.LogError(ex, "The admin password for {Service} could not be decrypted.", service.Name);

            // Nothing was ever run, so this refusal is certain in the way an operator needs.
            return (false, "This database's own credentials could not be read.", true);
        }

        try
        {
            var exit = await docker.RunOneOffAsync(new DockerOneOffRequest(
                Image: command.Image,
                Command: command.Command,
                Binds: [],
                Env: DatabaseGrantSql.Environment(service.Type, adminPassword),
                NetworkMode: networkName), null, ct);

            // The client's own output is not returned to the caller: it can quote the statement,
            // and the statement contains the new password.
            return exit == 0 ? (true, null, true) : (false, $"The database refused to {what}.", true);
        }
        catch (Exception ex)
        {
            // Cancellation lands here too, and deliberately so. A cancelled token after the client
            // was started tells us nothing about what the database did with the statement, and
            // rethrowing would replace this sentence with a stack trace on somebody's error page.
            logger.LogWarning(ex, "Could not {What} on {Service}.", what, service.Name);
            return (false,
                $"Harbora lost contact with the database while trying to {what}, so whether that " +
                "happened is not known.", false);
        }
    }
}
