using Harbora.Application.Abstractions;
using Harbora.Domain.Services;
using Harbora.Infrastructure.Nodes;
using Microsoft.Extensions.Logging;

namespace Harbora.Infrastructure.Services;

/// <summary>
/// Creates and removes the login an external grant uses, by running the engine's own client against
/// the database on its private network.
///
/// A one-off container rather than a connection from the panel: it needs no driver for every engine
/// Harbora supports, it reaches the database over the network the database is actually on, and it
/// leaves nothing behind. The statements come from <see cref="DatabaseGrantSql"/>, which refuses to
/// build anything out of a value it has not proved is safe.
///
/// <para>
/// HARBORA-0059: this used to take an <c>IDockerEngine</c> directly, which is always the panel's own
/// daemon — so every grant on a database placed on another server ran the client here instead, on a
/// network of that name that does not exist on this machine. Unlike the external-access gateway or
/// the admin tool, a grant needs nothing published back to the panel: the client and the database it
/// talks to both live on whichever server holds the data, so there is no reason to insist on the
/// local engine the way <see cref="DockerTcpGateway"/> does. It only has to run on the <b>right</b>
/// one, resolved through <see cref="IServerEngineFactory"/> like every other cross-server reach on
/// this platform.
/// </para>
/// </summary>
public sealed class DatabaseGrantExecutor(
    IServerEngineFactory engines,
    ISecretProtector protector,
    ILogger<DatabaseGrantExecutor> logger)
{
    public async Task<(bool Ok, string? Error)> CreateAsync(
        ManagedService service, string networkName, string username, string password, CancellationToken ct)
    {
        if (!DatabaseGrantSql.Supports(service.Type))
            return (false, DatabaseGrantSql.UnsupportedReason(service.Type));

        var command = DatabaseGrantSql.Create(
            service.Type, service.ContainerName, service.InternalPort,
            service.Username, service.DatabaseName, username, password);

        // Null means a value failed the safety check. Refused rather than escaped: everything here
        // is generated by Harbora, so anything outside the alphabet is a bug or an attack.
        if (command is null) return (false, "That database's details cannot be used to make a login.");

        var run = await RunAsync(service, networkName, command, "create the login", ct);
        return (run.Ok, run.Error);
    }

    /// <summary>
    /// Creates a new logical database on the instance (D1, 2026-08-25 shared-databases plan) and a
    /// login scoped to it — the same two-step shape <see cref="CreateAsync"/> already performs on a
    /// database that exists, extended rather than duplicated: <c>DatabaseGrantSql.CreateDatabase</c>
    /// runs first, then this reuses <see cref="DatabaseGrantSql.Create"/> exactly as it already runs
    /// for an external-access grant, just pointed at the new database instead of
    /// <see cref="ManagedService.DatabaseName"/>.
    ///
    /// <para>
    /// If the login cannot be created, the database it was meant to own is dropped again rather than
    /// left behind empty and unreachable — a database Harbora made and nobody can connect to is the
    /// same defect class as a row Harbora has and the engine does not, just facing the other way.
    /// </para>
    /// </summary>
    public async Task<(bool Ok, string? Error)> CreateDatabaseAsync(
        ManagedService service, string networkName, string database, string username, string password,
        CancellationToken ct)
    {
        if (!DatabaseGrantSql.Supports(service.Type))
            return (false, DatabaseGrantSql.UnsupportedReason(service.Type));

        var createDatabase = DatabaseGrantSql.CreateDatabase(
            service.Type, service.ContainerName, service.InternalPort,
            service.Username, service.DatabaseName, database);

        if (createDatabase is null) return (false, "That database's name cannot be used to create it.");

        var madeDatabase = await RunAsync(service, networkName, createDatabase, "create the database", ct);
        if (!madeDatabase.Ok) return (madeDatabase.Ok, madeDatabase.Error);

        var grant = DatabaseGrantSql.Create(
            service.Type, service.ContainerName, service.InternalPort,
            service.Username, database, username, password);

        if (grant is null)
        {
            await DropDatabaseOnlyAsync(service, networkName, database, ct);
            return (false, "That login's details cannot be used to make a login.");
        }

        var madeLogin = await RunAsync(service, networkName, grant, "create the login", ct);
        if (!madeLogin.Ok)
        {
            await DropDatabaseOnlyAsync(service, networkName, database, ct);
            return (madeLogin.Ok, madeLogin.Error);
        }

        return (true, null);
    }

    /// <summary>
    /// Removes a logical database and the login that owns it (D1, 2026-08-25 shared-databases plan).
    ///
    /// The login goes first, while the database it owns objects in still exists — reusing
    /// <see cref="DatabaseGrantSql.Drop"/> exactly as an external-access grant's revoke already does,
    /// just pointed at the logical database rather than <see cref="ManagedService.DatabaseName"/> —
    /// and only once that has succeeded is the database itself dropped. Reversing the order would ask
    /// PostgreSQL to reassign objects out of a database that no longer exists.
    /// </summary>
    public async Task<(bool Ok, string? Error)> DropDatabaseAsync(
        ManagedService service, string networkName, string database, string username, CancellationToken ct)
    {
        if (!DatabaseGrantSql.Supports(service.Type)) return (true, null);

        var dropLogin = DatabaseGrantSql.Drop(
            service.Type, service.ContainerName, service.InternalPort, service.Username, database, username);

        if (dropLogin is not null)
        {
            var loginResult = await RunAsync(service, networkName, dropLogin, "remove the database's login", ct);
            if (!loginResult.Ok) return (loginResult.Ok, loginResult.Error);
        }

        return await DropDatabaseOnlyAsync(service, networkName, database, ct);
    }

    /// <summary>The database statement alone, shared by a successful <see cref="DropDatabaseAsync"/>
    /// and the rollback <see cref="CreateDatabaseAsync"/> runs when the login side failed.</summary>
    private async Task<(bool Ok, string? Error)> DropDatabaseOnlyAsync(
        ManagedService service, string networkName, string database, CancellationToken ct)
    {
        var command = DatabaseGrantSql.DropDatabase(
            service.Type, service.ContainerName, service.InternalPort,
            service.Username, service.DatabaseName, database);

        if (command is null) return (false, "That database's name cannot be used in a statement.");

        var run = await RunAsync(service, networkName, command, "remove the database", ct);
        return (run.Ok, run.Error);
    }

    /// <summary>
    /// Replaces the password on a login that is already there.
    ///
    /// <para>
    /// Unsupported engines are refused rather than silently accepted, unlike <see cref="DropAsync"/>:
    /// a drop that has nothing to drop has already achieved what it was for, but a rotation that
    /// changed nothing must not come back as success — the caller hands the returned password to a
    /// person on the strength of that answer.
    /// </para>
    ///
    /// <para>
    /// This is the one caller that needs <c>Answered</c>, which is why it returns it. A refusal the
    /// client reported and a refusal nobody reported are different facts about a customer's
    /// database, and only the first of them means the old password is still the live one.
    /// </para>
    /// </summary>
    public Task<(bool Ok, string? Error, bool Answered)> RotateAsync(
        ManagedService service, string networkName, string username, string password, CancellationToken ct)
    {
        if (!DatabaseGrantSql.Supports(service.Type))
            return Task.FromResult((false, (string?)DatabaseGrantSql.UnsupportedReason(service.Type), true));

        var command = DatabaseGrantSql.Rotate(
            service.Type, service.ContainerName, service.InternalPort,
            service.Username, service.DatabaseName, username, password);

        // Nothing was built, so nothing was run — the answer is as certain as it gets.
        if (command is null)
            return Task.FromResult((false, (string?)"That login's details cannot be used in a statement.", true));

        return RunAsync(service, networkName, command, "change the login's password", ct);
    }

    public async Task<(bool Ok, string? Error)> DropAsync(
        ManagedService service, string networkName, string username, CancellationToken ct)
    {
        if (!DatabaseGrantSql.Supports(service.Type)) return (true, null);

        var command = DatabaseGrantSql.Drop(
            service.Type, service.ContainerName, service.InternalPort,
            service.Username, service.DatabaseName, username);

        if (command is null) return (false, "That login's name cannot be used in a statement.");

        var run = await RunAsync(service, networkName, command, "remove the login", ct);
        return (run.Ok, run.Error);
    }

    /// <param name="what">
    /// The operation, in the words the operator reads. It goes into the refusal and into the log.
    /// </param>
    /// <returns>
    /// <c>Answered</c> is whether the client gave a verdict — an exit code, or a refusal raised
    /// before anything was run.
    ///
    /// <para>
    /// False is <b>everything else the one-off can throw</b>, and it is deliberately not narrower
    /// than that: the image could not be pulled, the container could not be created or started, the
    /// token was already cancelled and nothing ran at all — through to the container running the
    /// statement and the exit code being lost on the way out. Those are very different facts about a
    /// customer's database and nothing here can tell them apart, so the flag claims only the weak
    /// thing they share: <i>this did not report back, so assume the statement may have landed.</i> A
    /// caller holding a secret that statement carried must not throw it away on that; saying only
    /// "could not be reached" invites exactly that reading, and a message that asserts the database
    /// <i>was</i> told something overshoots in the other direction.
    /// </para>
    /// </returns>
    private async Task<(bool Ok, string? Error, bool Answered)> RunAsync(
        ManagedService service, string networkName, GrantCommand command, string what, CancellationToken ct)
    {
        string adminPassword;
        try { adminPassword = protector.Unprotect(service.EncryptedPassword); }
        catch (Exception ex)
        {
            logger.LogError(ex, "The admin password for {Service} could not be decrypted.", service.Name);

            // Nothing was ever run, so this refusal is certain in the way an operator needs.
            return (false, "This database's own credentials could not be read.", true);
        }

        // Resolved per the database's own server rather than assumed to be this panel's daemon. A
        // server this cannot reach at all — no agent endpoint, no enrolled node, a revoked one —
        // throws before anything is attempted, so the refusal is as certain as the decrypt failure
        // above: nothing here was ever risked.
        IDockerEngine docker;
        try
        {
            docker = await engines.ResolveAsync(service.ServerId, ct);
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Could not reach the server holding {Service} to {What}.", service.Name, what);
            return (false,
                $"The server holding '{service.Name}' could not be reached, so nothing was attempted " +
                $"to {what}. {ex.Message}", true);
        }

        try
        {
            var exit = await docker.RunOneOffAsync(new DockerOneOffRequest(
                Image: command.Image,
                Command: command.Command,
                Binds: [],
                Env: DatabaseGrantSql.Environment(service.Type, adminPassword),
                NetworkMode: networkName), null, ct);

            // The client's own output is not returned to the caller: it can quote the statement,
            // and the statement contains the new password.
            return exit == 0 ? (true, null, true) : (false, $"The database refused to {what}.", true);
        }
        catch (NodeCapabilityException ex)
        {
            // Not a network hiccup: a v1 node's command allowlist has no verb for running a one-off
            // container to completion, on purpose (see NodeWorkloadEngine's own class comment), so
            // this is thrown locally before the node is ever contacted. That makes it exactly as
            // certain as the decrypt failure above — nothing was risked — and it deserves a refusal
            // that names the real constraint rather than the generic "lost contact" below, which
            // would send an operator chasing a flaky connection that was never the problem.
            logger.LogWarning(ex, "Could not {What} on {Service}: the node it runs on has no one-off verb.", what, service.Name);
            return (false,
                $"'{service.Name}' runs on a node that cannot {what}: {ex.Message}", true);
        }
        catch (Exception ex)
        {
            // Cancellation lands here too, and deliberately so. A cancelled token after the client
            // was started tells us nothing about what the database did with the statement, and
            // rethrowing would replace this sentence with a stack trace on somebody's error page.
            logger.LogWarning(ex, "Could not {What} on {Service}.", what, service.Name);
            return (false,
                $"Harbora lost contact with the database while trying to {what}, so whether that " +
                "happened is not known.", false);
        }
    }
}
