using Harbora.Application.Abstractions;
using Harbora.Domain.Services;
using Microsoft.Extensions.Logging;

namespace Harbora.Infrastructure.Services;

/// <summary>
/// Creates and removes the login an external grant uses, by running the engine's own client against
/// the database on its private network.
///
/// A one-off container rather than a connection from the panel: it needs no driver for every engine
/// Harbora supports, it reaches the database over the network the database is actually on, and it
/// leaves nothing behind. The statements come from <see cref="DatabaseGrantSql"/>, which refuses to
/// build anything out of a value it has not proved is safe.
/// </summary>
public sealed class DatabaseGrantExecutor(
    IDockerEngine docker,
    ISecretProtector protector,
    ILogger<DatabaseGrantExecutor> logger)
{
    public async Task<(bool Ok, string? Error)> CreateAsync(
        ManagedService service, string networkName, string username, string password, CancellationToken ct)
    {
        if (!DatabaseGrantSql.Supports(service.Type))
            return (false, DatabaseGrantSql.UnsupportedReason(service.Type));

        var command = DatabaseGrantSql.Create(
            service.Type, service.ContainerName, service.InternalPort,
            service.Username, service.DatabaseName, username, password);

        // Null means a value failed the safety check. Refused rather than escaped: everything here
        // is generated by Harbora, so anything outside the alphabet is a bug or an attack.
        if (command is null) return (false, "That database's details cannot be used to make a login.");

        return await RunAsync(service, networkName, command, "create the login", ct);
    }

    /// <summary>
    /// Replaces the password on a login that is already there.
    ///
    /// Unsupported engines are refused rather than silently accepted, unlike <see cref="DropAsync"/>:
    /// a drop that has nothing to drop has already achieved what it was for, but a rotation that
    /// changed nothing must not come back as success — the caller hands the returned password to a
    /// person on the strength of that answer.
    /// </summary>
    public async Task<(bool Ok, string? Error)> RotateAsync(
        ManagedService service, string networkName, string username, string password, CancellationToken ct)
    {
        if (!DatabaseGrantSql.Supports(service.Type))
            return (false, DatabaseGrantSql.UnsupportedReason(service.Type));

        var command = DatabaseGrantSql.Rotate(
            service.Type, service.ContainerName, service.InternalPort,
            service.Username, service.DatabaseName, username, password);

        if (command is null) return (false, "That login's details cannot be used in a statement.");

        return await RunAsync(service, networkName, command, "change the login's password", ct);
    }

    public async Task<(bool Ok, string? Error)> DropAsync(
        ManagedService service, string networkName, string username, CancellationToken ct)
    {
        if (!DatabaseGrantSql.Supports(service.Type)) return (true, null);

        var command = DatabaseGrantSql.Drop(
            service.Type, service.ContainerName, service.InternalPort,
            service.Username, service.DatabaseName, username);

        if (command is null) return (false, "That login's name cannot be used in a statement.");

        return await RunAsync(service, networkName, command, "remove the login", ct);
    }

    private async Task<(bool Ok, string? Error)> RunAsync(
        ManagedService service, string networkName, GrantCommand command, string what, CancellationToken ct)
    {
        string adminPassword;
        try { adminPassword = protector.Unprotect(service.EncryptedPassword); }
        catch (Exception ex)
        {
            logger.LogError(ex, "The admin password for {Service} could not be decrypted.", service.Name);
            return (false, "This database's own credentials could not be read.");
        }

        try
        {
            var exit = await docker.RunOneOffAsync(new DockerOneOffRequest(
                Image: command.Image,
                Command: command.Command,
                Binds: [],
                Env: DatabaseGrantSql.Environment(service.Type, adminPassword),
                NetworkMode: networkName), null, ct);

            // The client's own output is not returned to the caller: it can quote the statement,
            // and the statement contains the new password.
            return exit == 0 ? (true, null) : (false, $"The database refused to {what}.");
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Could not {What} on {Service}.", what, service.Name);
            return (false, $"The database could not be reached to {what}.");
        }
    }
}
