using Harbora.Domain.Common;

namespace Harbora.Infrastructure.Services;

/// <summary>The command to run, and the client image that can run it.</summary>
/// <param name="Image">A client for this engine, pinned to a major so patches are picked up.</param>
/// <param name="Command">argv, never a shell string — see the class remarks.</param>
public sealed record GrantCommand(string Image, IReadOnlyList<string> Command);

/// <summary>
/// The statements that create and remove an external login on a managed database.
///
/// **Every value here ends up inside SQL**, so the rule is: nothing is interpolated that has not
/// first been proved to be from the generated alphabet. `DatabaseCredentialManager` produces
/// usernames and passwords from letters and digits only, and <see cref="IsSafe"/> insists on it
/// rather than trusting it — the day somebody adds a "use my own username" field, this refuses it
/// instead of quietly building `DROP TABLE` for them.
///
/// Commands are argv arrays, not shell strings. A shell string reintroduces the whole quoting
/// problem one layer down, where nothing is checking.
/// </summary>
public static class DatabaseGrantSql
{
    /// <summary>Engines this can issue a login on. Anything else is refused rather than faked.</summary>
    public static bool Supports(ManagedServiceType type) =>
        type is ManagedServiceType.PostgreSql or ManagedServiceType.MySql or ManagedServiceType.MariaDb;

    /// <summary>
    /// Whether a value may be put into a statement.
    ///
    /// Letters, digits and underscore. Deliberately narrower than "escape it properly": the values
    /// that reach here are generated by Harbora, so anything else is a bug or an attack, and both
    /// should stop rather than be encoded around.
    /// </summary>
    public static bool IsSafe(string? value) =>
        !string.IsNullOrEmpty(value)
        && value.Length <= 64
        && value.All(c => char.IsAsciiLetterOrDigit(c) || c == '_');

    /// <summary>
    /// Creates a login with read and write on the one database this service holds — not on the
    /// server. An external grant is for the customer's own data, and a role that can read every
    /// other database on the instance is a tenancy hole with a friendly name.
    /// </summary>
    public static GrantCommand? Create(
        ManagedServiceType type, string host, int port, string adminUser,
        string database, string username, string password)
    {
        if (!Supports(type)) return null;
        if (!IsSafe(username) || !IsSafe(password) || !IsSafe(database) || !IsSafe(adminUser)) return null;

        return type switch
        {
            ManagedServiceType.PostgreSql => new GrantCommand("postgres:16-alpine",
            [
                "psql", "-v", "ON_ERROR_STOP=1",
                "-h", host, "-p", port.ToString(), "-U", adminUser, "-d", database,
                "-c", $"CREATE USER \"{username}\" WITH PASSWORD '{password}';",
                "-c", $"GRANT CONNECT ON DATABASE \"{database}\" TO \"{username}\";",
                "-c", $"GRANT USAGE, CREATE ON SCHEMA public TO \"{username}\";",
                "-c", $"GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO \"{username}\";",
                "-c", $"GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO \"{username}\";",

                // Tables the customer creates after this point would otherwise be invisible to the
                // login that created them the next time they connect.
                "-c", $"ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO \"{username}\";"
            ]),

            // '%' because the connection arrives through the gateway container, whose address on the
            // private network is not knowable when the login is made. Which addresses may reach the
            // gateway at all is enforced at the gateway, where the real client IP still exists.
            _ => new GrantCommand("mariadb:11",
            [
                "mariadb", "-h", host, "-P", port.ToString(), "-u", adminUser,
                "-e", $"CREATE USER '{username}'@'%' IDENTIFIED BY '{password}'; " +
                      $"GRANT ALL PRIVILEGES ON `{database}`.* TO '{username}'@'%'; " +
                      "FLUSH PRIVILEGES;"
            ])
        };
    }

    /// <summary>
    /// Removes the login. Written so running it twice is success: the sweeper and somebody pressing
    /// revoke can race, and both must end with the login gone.
    /// </summary>
    public static GrantCommand? Drop(
        ManagedServiceType type, string host, int port, string adminUser,
        string database, string username)
    {
        if (!Supports(type)) return null;
        if (!IsSafe(username) || !IsSafe(database) || !IsSafe(adminUser)) return null;

        return type switch
        {
            ManagedServiceType.PostgreSql => new GrantCommand("postgres:16-alpine",
            [
                "psql", "-h", host, "-p", port.ToString(), "-U", adminUser, "-d", database,

                // Not ON_ERROR_STOP: a login that is already gone must not fail the revoke. The
                // privileges have to go before the role can, which is why this is four statements.
                "-c", $"REASSIGN OWNED BY \"{username}\" TO \"{adminUser}\";",
                "-c", $"DROP OWNED BY \"{username}\";",
                "-c", $"REVOKE ALL PRIVILEGES ON DATABASE \"{database}\" FROM \"{username}\";",
                "-c", $"DROP ROLE IF EXISTS \"{username}\";"
            ]),

            _ => new GrantCommand("mariadb:11",
            [
                "mariadb", "-h", host, "-P", port.ToString(), "-u", adminUser,
                "-e", $"DROP USER IF EXISTS '{username}'@'%'; FLUSH PRIVILEGES;"
            ])
        };
    }

    /// <summary>Environment for the client container — the admin password never goes in argv.</summary>
    public static IReadOnlyDictionary<string, string> Environment(
        ManagedServiceType type, string adminPassword) =>
        // Never argv. A password in a container's command line is visible in `docker inspect` and
        // in the host's process list for as long as the container runs, and `mariadb -p<pw>` is the
        // classic way that happens.
        type == ManagedServiceType.PostgreSql
            ? new Dictionary<string, string> { ["PGPASSWORD"] = adminPassword }
            : new Dictionary<string, string> { ["MYSQL_PWD"] = adminPassword };

    /// <summary>Why this engine cannot be opened, for a message somebody can act on.</summary>
    public static string UnsupportedReason(ManagedServiceType type) =>
        $"External access is not available for {type} yet. It is built for PostgreSQL, MySQL and MariaDB.";
}
