using Harbora.Domain.Common;

namespace Harbora.Infrastructure.Services;

/// <summary>The command to run, and the client image that can run it.</summary>
/// <param name="Image">A client for this engine, pinned to a major so patches are picked up.</param>
/// <param name="Command">argv, never a shell string — see the class remarks.</param>
public sealed record GrantCommand(string Image, IReadOnlyList<string> Command);

/// <summary>
/// The statements that create, re-password and remove an external login on a managed database.
///
/// **Every value here ends up inside SQL**, so the rule is: nothing is interpolated that has not
/// first been proved to be from the generated alphabet. `DatabaseCredentialManager` produces
/// usernames and passwords from letters and digits only, and <see cref="IsSafe"/> insists on it
/// rather than trusting it — the day somebody adds a "use my own username" field, this refuses it
/// instead of quietly building `DROP TABLE` for them.
///
/// Commands are argv arrays, not shell strings. A shell string reintroduces the whole quoting
/// problem one layer down, where nothing is checking.
/// </summary>
public static class DatabaseGrantSql
{
    /// <summary>Engines this can issue a login on. Anything else is refused rather than faked.</summary>
    public static bool Supports(ManagedServiceType type) =>
        type is ManagedServiceType.PostgreSql or ManagedServiceType.MySql or ManagedServiceType.MariaDb;

    /// <summary>
    /// Whether a value may be put into a statement.
    ///
    /// Letters, digits and underscore. Deliberately narrower than "escape it properly": the values
    /// that reach here are generated by Harbora, so anything else is a bug or an attack, and both
    /// should stop rather than be encoded around.
    /// </summary>
    public static bool IsSafe(string? value) =>
        !string.IsNullOrEmpty(value)
        && value.Length <= 64
        && value.All(c => char.IsAsciiLetterOrDigit(c) || c == '_');

    /// <summary>
    /// Creates a login with read and write on the one database this service holds — not on the
    /// server. An external grant is for the customer's own data, and a role that can read every
    /// other database on the instance is a tenancy hole with a friendly name.
    /// </summary>
    public static GrantCommand? Create(
        ManagedServiceType type, string host, int port, string adminUser,
        string database, string username, string password)
    {
        if (!Supports(type)) return null;
        if (!IsSafe(username) || !IsSafe(password) || !IsSafe(database) || !IsSafe(adminUser)) return null;

        return type switch
        {
            ManagedServiceType.PostgreSql => new GrantCommand("postgres:16-alpine",
            [
                "psql", "-v", "ON_ERROR_STOP=1",
                "-h", host, "-p", port.ToString(), "-U", adminUser, "-d", database,
                "-c", $"CREATE USER \"{username}\" WITH PASSWORD '{password}';",
                "-c", $"GRANT CONNECT ON DATABASE \"{database}\" TO \"{username}\";",
                "-c", $"GRANT USAGE, CREATE ON SCHEMA public TO \"{username}\";",
                "-c", $"GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO \"{username}\";",
                "-c", $"GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO \"{username}\";",

                // Tables the customer creates after this point would otherwise be invisible to the
                // login that created them the next time they connect.
                "-c", $"ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO \"{username}\";"
            ]),

            // '%' because the connection arrives through the gateway container, whose address on the
            // private network is not knowable when the login is made. Which addresses may reach the
            // gateway at all is enforced at the gateway, where the real client IP still exists.
            _ => new GrantCommand("mariadb:11",
            [
                "mariadb", "-h", host, "-P", port.ToString(), "-u", adminUser,
                "-e", $"CREATE USER '{username}'@'%' IDENTIFIED BY '{password}'; " +
                      $"GRANT ALL PRIVILEGES ON `{database}`.* TO '{username}'@'%'; " +
                      "FLUSH PRIVILEGES;"
            ])
        };
    }

    /// <summary>
    /// Creates a new logical database inside the instance (D1, 2026-08-25 shared-databases plan) —
    /// the statement that <c>DatabaseGrantExecutor.CreateDatabaseAsync</c> runs before it hands the
    /// new database to <see cref="Create"/> the way every other database on the instance already
    /// gets its login.
    ///
    /// <para>
    /// PostgreSQL refuses <c>CREATE DATABASE</c> on the connection that would run inside the database
    /// being created — it does not exist yet — so this connects to <paramref name="adminDatabase"/>,
    /// the instance's own default database, instead. MySQL/MariaDB have no such restriction: any
    /// connection can create any database, which is why their branch needs no separate anchor.
    /// </para>
    /// </summary>
    public static GrantCommand? CreateDatabase(
        ManagedServiceType type, string host, int port, string adminUser, string adminDatabase, string database)
    {
        if (!Supports(type)) return null;
        if (!IsSafe(database) || !IsSafe(adminUser)) return null;
        if (type == ManagedServiceType.PostgreSql && !IsSafe(adminDatabase)) return null;

        return type switch
        {
            ManagedServiceType.PostgreSql => new GrantCommand("postgres:16-alpine",
            [
                "psql", "-v", "ON_ERROR_STOP=1",
                "-h", host, "-p", port.ToString(), "-U", adminUser, "-d", adminDatabase,
                "-c", $"CREATE DATABASE \"{database}\";"
            ]),

            _ => new GrantCommand("mariadb:11",
            [
                "mariadb", "-h", host, "-P", port.ToString(), "-u", adminUser,
                "-e", $"CREATE DATABASE IF NOT EXISTS `{database}`;"
            ])
        };
    }

    /// <summary>
    /// Removes a logical database entirely — the counterpart of <see cref="CreateDatabase"/>, run
    /// only after <see cref="Drop"/> has already removed the login that owned objects inside it (see
    /// <c>DatabaseGrantExecutor.DropDatabaseAsync</c> for why the order cannot be reversed: an object
    /// cannot be reassigned out of a database that no longer exists).
    ///
    /// <c>IF EXISTS</c> on both branches, matching <see cref="Drop"/>: a database already gone must
    /// not fail a removal that has already achieved what it was for.
    /// </summary>
    public static GrantCommand? DropDatabase(
        ManagedServiceType type, string host, int port, string adminUser, string adminDatabase, string database)
    {
        if (!Supports(type)) return null;
        if (!IsSafe(database) || !IsSafe(adminUser)) return null;
        if (type == ManagedServiceType.PostgreSql && !IsSafe(adminDatabase)) return null;

        return type switch
        {
            ManagedServiceType.PostgreSql => new GrantCommand("postgres:16-alpine",
            [
                "psql", "-h", host, "-p", port.ToString(), "-U", adminUser, "-d", adminDatabase,
                "-c", $"DROP DATABASE IF EXISTS \"{database}\";"
            ]),

            _ => new GrantCommand("mariadb:11",
            [
                "mariadb", "-h", host, "-P", port.ToString(), "-u", adminUser,
                "-e", $"DROP DATABASE IF EXISTS `{database}`;"
            ])
        };
    }

    /// <summary>
    /// Changes the password on a login that already exists, leaving its privileges alone.
    ///
    /// The opposite of <see cref="Drop"/> on repetition: <c>ON_ERROR_STOP</c> is set and neither
    /// branch carries an <c>IF EXISTS</c>, so rotating a login the database does not have fails
    /// loudly. Reporting success there would hand somebody a password nothing will ever accept,
    /// while the old one — the one they wanted retired — kept working.
    ///
    /// <para>
    /// Both branches are also exactly <b>one</b> statement, which the caller depends on: it reads a
    /// non-zero exit as "the ALTER did not take" and discards the new password on the strength of
    /// it. A second statement that could fail after a successful ALTER would turn a completed
    /// rotation into a reported refusal and lose the only copy of a live credential. See the note on
    /// the MySQL branch, and <c>DatabaseAccessService.RotateAsync</c>'s <c>Answered</c> arm.
    /// </para>
    /// </summary>
    public static GrantCommand? Rotate(
        ManagedServiceType type, string host, int port, string adminUser,
        string database, string username, string password)
    {
        if (!Supports(type)) return null;
        if (!IsSafe(username) || !IsSafe(password) || !IsSafe(database) || !IsSafe(adminUser)) return null;

        return type switch
        {
            ManagedServiceType.PostgreSql => new GrantCommand("postgres:16-alpine",
            [
                "psql", "-v", "ON_ERROR_STOP=1",
                "-h", host, "-p", port.ToString(), "-U", adminUser, "-d", database,
                "-c", $"ALTER USER \"{username}\" WITH PASSWORD '{password}';"
            ]),

            // ALTER USER rather than SET PASSWORD: the latter needs the hash function whose name
            // changed between MySQL and MariaDB, and this one client image talks to both.
            //
            // One statement, and deliberately no trailing FLUSH PRIVILEGES — unlike Create and Drop.
            // The flush was never doing anything: an account-management statement updates the
            // in-memory grant tables itself, and the flush is for rows written into mysql.* by hand.
            // But it could still *fail*. It needs the RELOAD privilege and errors 1227 without it,
            // and this connects as the service's own admin account — "harbora", the name every
            // managed service is provisioned with, on both provisioning paths — not as root. On any
            // install where the ALTER is permitted and the reload is not, the batch would exit
            // non-zero after the password had already changed, and the caller reads a non-zero exit
            // as "the ALTER did not take" and throws the new password away. A statement that cannot
            // change anything could still cost an operator the only copy of a live credential.
            //
            // The other two keep theirs, and they are not the same case:
            //  * Drop's is harmless. CloseAsync discards DropAsync's result and closes the row
            //    either way, so a 1227 after DROP USER changes nothing anybody sees.
            //  * Create's is NOT harmless, and is left only because it is outside this task. The
            //    same 1227 would land after CREATE USER and GRANT have both succeeded; IssueAsync
            //    then marks the grant Failed and returns the error *without* calling DropAsync —
            //    unlike its endpoint-failure branch, which does undo the login — leaving a live
            //    '%'-host login with ALL PRIVILEGES on a customer's database that Harbora has
            //    recorded as never created. Reported rather than fixed; see the task report.
            _ => new GrantCommand("mariadb:11",
            [
                "mariadb", "-h", host, "-P", port.ToString(), "-u", adminUser,
                "-e", $"ALTER USER '{username}'@'%' IDENTIFIED BY '{password}';"
            ])
        };
    }

    /// <summary>
    /// Whether this engine can rename an existing database in place, losslessly and atomically (D3,
    /// 2026-08-25 shared-databases plan). PostgreSQL's <c>ALTER DATABASE … RENAME TO</c> is exactly
    /// that — one statement, and every grant PostgreSQL already holds on the database is tracked by
    /// OID, not by name, so it survives untouched.
    ///
    /// <para>
    /// MySQL and MariaDB have no equivalent: the <c>RENAME DATABASE</c> statement MySQL shipped
    /// briefly was removed in 5.1.23 because it silently dropped triggers, stored routines and
    /// per-object privileges bound to the old schema name — data loss dressed up as a rename. The
    /// only safe substitute (dump, recreate under the new name, restore, drop the old one) is a full
    /// backup/restore cycle wearing a rename's name, not the same operation, so it is refused by name
    /// here rather than offered as something it is not.
    /// </para>
    /// </summary>
    public static bool SupportsRename(ManagedServiceType type) => type == ManagedServiceType.PostgreSql;

    /// <summary>Why this engine cannot rename a database in place, for a message somebody can act on.</summary>
    public static string UnsupportedRenameReason(ManagedServiceType type) =>
        $"Renaming a database in place is not available for {type}. PostgreSQL can rename one " +
        "atomically; MySQL and MariaDB have no lossless equivalent, so this is refused rather than " +
        "offered as something it is not.";

    /// <summary>
    /// Renames a database that already exists (D3, 2026-08-25 shared-databases plan) — connects to
    /// <paramref name="adminDatabase"/> rather than <paramref name="oldName"/> for the same reason
    /// <see cref="CreateDatabase"/> does: PostgreSQL refuses to rename the database the connection
    /// is actually using.
    /// </summary>
    public static GrantCommand? Rename(
        ManagedServiceType type, string host, int port, string adminUser, string adminDatabase,
        string oldName, string newName)
    {
        if (!SupportsRename(type)) return null;
        if (!IsSafe(oldName) || !IsSafe(newName) || !IsSafe(adminUser) || !IsSafe(adminDatabase)) return null;

        return new GrantCommand("postgres:16-alpine",
        [
            "psql", "-v", "ON_ERROR_STOP=1",
            "-h", host, "-p", port.ToString(), "-U", adminUser, "-d", adminDatabase,
            "-c", $"ALTER DATABASE \"{oldName}\" RENAME TO \"{newName}\";"
        ]);
    }

    /// <summary>
    /// Removes the login. Written so running it twice is success: the sweeper and somebody pressing
    /// revoke can race, and both must end with the login gone.
    /// </summary>
    public static GrantCommand? Drop(
        ManagedServiceType type, string host, int port, string adminUser,
        string database, string username)
    {
        if (!Supports(type)) return null;
        if (!IsSafe(username) || !IsSafe(database) || !IsSafe(adminUser)) return null;

        return type switch
        {
            ManagedServiceType.PostgreSql => new GrantCommand("postgres:16-alpine",
            [
                "psql", "-h", host, "-p", port.ToString(), "-U", adminUser, "-d", database,

                // Not ON_ERROR_STOP: a login that is already gone must not fail the revoke. The
                // privileges have to go before the role can, which is why this is four statements.
                "-c", $"REASSIGN OWNED BY \"{username}\" TO \"{adminUser}\";",
                "-c", $"DROP OWNED BY \"{username}\";",
                "-c", $"REVOKE ALL PRIVILEGES ON DATABASE \"{database}\" FROM \"{username}\";",
                "-c", $"DROP ROLE IF EXISTS \"{username}\";"
            ]),

            _ => new GrantCommand("mariadb:11",
            [
                "mariadb", "-h", host, "-P", port.ToString(), "-u", adminUser,
                "-e", $"DROP USER IF EXISTS '{username}'@'%'; FLUSH PRIVILEGES;"
            ])
        };
    }

    /// <summary>Engines with a pgvector story at all (1.7, pgvector-as-option plan). PostgreSQL only
    /// — pgvector is a PostgreSQL extension; MySQL and MariaDB have nothing resembling it.</summary>
    public static bool SupportsVectorExtension(ManagedServiceType type) => type == ManagedServiceType.PostgreSql;

    /// <summary>Why this engine cannot have the vector extension, for a message somebody can act on.</summary>
    public static string VectorExtensionUnsupportedReason(ManagedServiceType type) =>
        $"pgvector is a PostgreSQL extension. {type} has no vector-extension story.";

    /// <summary>
    /// Installs pgvector inside one logical database (1.7, pgvector-as-option plan). <c>IF NOT
    /// EXISTS</c> so pressing the button twice, or reaching a database that already has it, is a
    /// success rather than an error — the same idempotence <see cref="CreateDatabase"/>'s MariaDB
    /// branch already relies on for the same reason.
    ///
    /// <para>
    /// Deliberately makes no attempt to know in advance whether the instance's own running image
    /// actually carries the extension's files: <c>CREATE EXTENSION</c> either succeeds or fails with
    /// Postgres's own reason (most commonly, against the plain <c>postgres</c> image: no
    /// <c>vector.control</c> to load), and reporting that reason back to the caller is more honest
    /// than a capability flag Harbora keeps beside it — a flag and the engine it describes can drift;
    /// this statement's own exit code cannot.
    /// </para>
    ///
    /// <para>
    /// Connects as the instance's own admin login, exactly like <see cref="CreateDatabase"/> — a
    /// freshly created per-database login has not necessarily been granted anything beyond its own
    /// tables (see <see cref="Create"/>), while the admin login this instance was provisioned with
    /// always has the rights <c>CREATE EXTENSION</c> needs.
    /// </para>
    /// </summary>
    public static GrantCommand? CreateVectorExtension(
        ManagedServiceType type, string host, int port, string adminUser, string database)
    {
        if (!SupportsVectorExtension(type)) return null;
        if (!IsSafe(database) || !IsSafe(adminUser)) return null;

        return new GrantCommand("postgres:16-alpine",
        [
            "psql", "-v", "ON_ERROR_STOP=1",
            "-h", host, "-p", port.ToString(), "-U", adminUser, "-d", database,
            "-c", "CREATE EXTENSION IF NOT EXISTS vector;"
        ]);
    }

    /// <summary>Environment for the client container — the admin password never goes in argv.</summary>
    public static IReadOnlyDictionary<string, string> Environment(
        ManagedServiceType type, string adminPassword) =>
        // Never argv. A password in a container's command line is visible in `docker inspect` and
        // in the host's process list for as long as the container runs, and `mariadb -p<pw>` is the
        // classic way that happens.
        type == ManagedServiceType.PostgreSql
            ? new Dictionary<string, string> { ["PGPASSWORD"] = adminPassword }
            : new Dictionary<string, string> { ["MYSQL_PWD"] = adminPassword };

    /// <summary>Why this engine cannot be opened, for a message somebody can act on.</summary>
    public static string UnsupportedReason(ManagedServiceType type) =>
        $"External access is not available for {type} yet. It is built for PostgreSQL, MySQL and MariaDB.";
}
