using Harbora.Domain.Common;

namespace Harbora.Application.Abstractions;

/// <summary>
/// Provisions and manages backing services (databases/caches) as containers on the shared
/// Harbora network, so apps can reach them by container name. Credentials are generated by
/// Harbora and stored encrypted; only masked connection info is shown by default.
/// </summary>
public interface IManagedServiceEngine
{
    /// <summary>The service types Harbora can create, for the "new service" picker.</summary>
    IReadOnlyList<ServiceCatalogEntry> Catalog { get; }

    /// <summary>Queue creation of the container for an already-persisted service row.</summary>
    Task QueueProvisionAsync(Guid serviceId, CancellationToken ct);

    Task StartAsync(Guid serviceId, CancellationToken ct);
    Task StopAsync(Guid serviceId, CancellationToken ct);
    Task RemoveAsync(Guid serviceId, bool deleteData, CancellationToken ct);

    /// <summary>Builds connection info (decrypting the password) for the details screen / attach flow.</summary>
    Task<ServiceConnectionInfo> GetConnectionInfoAsync(Guid serviceId, CancellationToken ct);

    /// <summary>
    /// Environment variables to inject into an app when a service is attached, keyed by var name.
    /// Values contain the real credentials (the caller marks them secret + encrypts).
    /// </summary>
    Task<IReadOnlyDictionary<string, string>> BuildAttachEnvAsync(Guid serviceId, CancellationToken ct);
}

public sealed record ServiceCatalogEntry(
    ManagedServiceType Type,
    string DisplayName,
    string DisplayNameFa,
    string DefaultImage,
    IReadOnlyList<string> Versions,
    int InternalPort,
    bool HasDatabaseName);

public sealed record ServiceConnectionInfo(
    string Host,
    int Port,
    string Username,
    string Password,
    string? Database,
    string ConnectionString,
    string ConnectionStringMasked);
