using Harbora.Domain.Common;

namespace Harbora.Application.Abstractions;

/// <summary>
/// Provisions and manages backing services (databases/caches) as containers on the shared
/// Harbora network, so apps can reach them by container name. Credentials are generated by
/// Harbora and stored encrypted; only masked connection info is shown by default.
/// </summary>
public interface IManagedServiceEngine
{
    /// <summary>The service types Harbora can create, for the "new service" picker.</summary>
    IReadOnlyList<ServiceCatalogEntry> Catalog { get; }

    /// <summary>Queue creation of the container for an already-persisted service row.</summary>
    Task QueueProvisionAsync(Guid serviceId, CancellationToken ct);

    Task StartAsync(Guid serviceId, CancellationToken ct);
    Task StopAsync(Guid serviceId, CancellationToken ct);
    Task RemoveAsync(Guid serviceId, bool deleteData, CancellationToken ct);

    /// <summary>
    /// Measures the data volume and records the figure with the moment it was taken. Explicit rather
    /// than automatic: it walks the whole directory, which is minutes on a large database.
    /// </summary>
    Task<long?> MeasureStorageAsync(Guid serviceId, CancellationToken ct);

    /// <summary>
    /// Replaces the database password and rewrites it into every app that was attached to it.
    /// Returns the apps that must be redeployed before they will use the new one — by id, not only
    /// by display name (P4, 2026-08-17 app-environment-management design), so a caller can act on
    /// the answer rather than merely print it: the confirmation page this feeds queues a redeploy
    /// per <see cref="RotatedApp.AppId"/>.
    /// </summary>
    Task<IReadOnlyList<RotatedApp>> RotatePasswordAsync(Guid serviceId, CancellationToken ct);

    /// <summary>
    /// Connects to the database from its own private network, the way a service would. Returns null
    /// on success, or a sentence describing what to go and fix.
    /// </summary>
    Task<string?> TestConnectionAsync(Guid serviceId, CancellationToken ct);

    /// <summary>Builds connection info (decrypting the password) for the details screen / attach flow.</summary>
    Task<ServiceConnectionInfo> GetConnectionInfoAsync(Guid serviceId, CancellationToken ct);

    /// <summary>
    /// Environment variables to inject into an app when a service is attached, keyed by var name.
    /// Values contain the real credentials (the caller marks them secret + encrypts).
    /// </summary>
    Task<IReadOnlyDictionary<string, string>> BuildAttachEnvAsync(Guid serviceId, CancellationToken ct);

    /// <summary>
    /// Sets a Redis instance's <c>maxmemory</c>/<c>maxmemory-policy</c>. Stored unconditionally so a
    /// later rebuild bakes it into the container's own command line, and applied live through
    /// <c>CONFIG SET</c> immediately when the instance is running — see
    /// <see cref="RedisMemoryPolicyOutcome"/> for why those are two different facts the caller must
    /// be told apart.
    /// </summary>
    /// <param name="policy">A key from <c>RedisMemoryPolicy.Choices</c>, or null.</param>
    /// <param name="maxMemoryBytes">Zero for no cap.</param>
    /// <remarks>
    /// Throws <c>RedisMemoryPolicyRefusedException</c> (<c>Harbora.Infrastructure.Services</c>) when
    /// the pair is not one Harbora will apply — see <c>RedisMemoryPolicy.WhyRefused</c>. Not a
    /// <c>cref</c>: this project does not reference Infrastructure, which is where that type lives.
    /// </remarks>
    Task<RedisMemoryPolicyOutcome> UpdateRedisMemoryPolicyAsync(
        Guid serviceId, string? policy, long maxMemoryBytes, CancellationToken ct);

    /// <summary>
    /// Ends a read replica's recovery mode and makes it an ordinary, independent, writable instance
    /// (3.2, round-2 market-gaps plan). Returns false with a reason for every refusal — not a replica,
    /// not running, or the engine itself refused the promotion — never throws for an ordinary refusal.
    /// </summary>
    Task<(bool Ok, string? Error)> PromoteReplicaAsync(Guid replicaId, CancellationToken ct);
}

public sealed record ServiceCatalogEntry(
    ManagedServiceType Type,
    string DisplayName,
    string DisplayNameFa,
    string DefaultImage,
    IReadOnlyList<string> Versions,
    int InternalPort,
    bool HasDatabaseName);

/// <summary>One app whose environment was rewritten by a password rotation.</summary>
public sealed record RotatedApp(Guid AppId, string Name);

public sealed record ServiceConnectionInfo(
    string Host,
    int Port,
    string Username,
    string Password,
    string? Database,
    string ConnectionString,
    string ConnectionStringMasked);

/// <summary>
/// What happened when a Redis instance's memory policy was saved.
/// </summary>
/// <param name="WasRunning">
/// Whether the container was running at the moment of the save. False means there was nothing to
/// reach live — the setting is stored and will be baked into the container's own command line the
/// next time it is provisioned.
/// </param>
/// <param name="AppliedLive">
/// True when <c>CONFIG SET</c> reached the running instance and it accepted the new value. Meaningless
/// when <see cref="WasRunning"/> is false.
/// </param>
/// <param name="LiveApplyError">
/// What the running instance said when it refused the live change, or null when nothing was
/// attempted or it succeeded. Named rather than swallowed — "the setting was saved" is not the same
/// claim as "the setting is in effect", and a refusal here is exactly the gap between the two.
/// </param>
public sealed record RedisMemoryPolicyOutcome(bool WasRunning, bool AppliedLive, string? LiveApplyError);
